
export const SHOP_CREATE_REQUEST = "SHOP_CREATE_REQUEST";
export const SHOP_CREATE_SUCCESS = "SHOP_CREATE_SUCCESS";
export const SHOP_CREATE_FAIL = "SHOP_CREATE_FAIL";
export const SHOP_CREATE_RESET = "SHOP_CREATE_RESET";


export const SHOP_UPDATE_REQUEST = "SHOP_UPDATE_REQUEST";
export const SHOP_UPDATE_SUCCESS = "SHOP_UPDATE_SUCCESS";
export const SHOP_UPDATE_FAIL = "SHOP_UPDATE_FAIL";
export const SHOP_UPDATE_RESET = "SHOP_UPDATE_RESET";


export const SHOP_DELETE_REQUEST = "SHOP_DELETE_REQUEST";
export const SHOP_DELETE_SUCCESS = "SHOP_DELETE_SUCCESS";
export const SHOP_DELETE_FAIL = "SHOP_DELETE_FAIL";
export const SHOP_DELETE_RESET = "SHOP_DELETE_RESET";


export const SHOP_GET_REQUEST = "SHOP_GET_REQUEST";
export const SHOP_GET_SUCCESS = "SHOP_GET_SUCCESS";
export const SHOP_GET_FAIL = "SHOP_GET_FAIL";
export const SHOP_GET_RESET = "SHOP_GET_RESET";


export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";
export const SHOP_DETAILS_RESET = "SHOP_DETAILS_RESET";
